### ISSUE TITLE
Updates to UTM Link Builder

### ISSUE THREAD

**Issue by andrewneuro** [ichliebedich/tracker#11]
@dioptre I just made some changes to the form fields. Check that out first. We need to make some further changes to the UI to make it ready, easy, and accurate for end-users (Veit in particular)...

1. Can we hide tracking server field? It's my understanding (a) this will always be the same? and (b) end-user won't know what this is or does? OR move it to advanced options.

2. Can we hide Your username? As it will mostly always be the same value. Can we tie it to the admin account? Not sure how this value ties back into the link? OR move it to advanced options.

3. Also need to clarify and make sure that if a manual link is created and shared (e.g. https://homodea.com/courses/victory-and-peace?utm_source=blah-blah) that the analytics will pick this up accurately. (I.e. that the tracker link generator is not always required and it will work without it?)

4. Also need to clarify and make sure that when the user clicks one of these generated links, the url in the browser does form into https://homodea.com/courses/victory-and-peace?utm_source=blah-blah. This is critical for Google Analytics to pick up UTM accurately.

**Comment by hilsbos** [comment]
@andrewneuro shall this stay here? do we need to pm board? please take care of this and ping me with an update. thx
