### ISSUE TITLE
Load-Testing Stats

### ISSUE THREAD

**Issue by cyberjunk** [ichliebedich/tracker#4]
@dioptre 

Leaving this here for review. Tracker seems to work super nicely after the latest changes.
ELB metrics show about a million tracker requests per minute (~17.000 per second) all with 200 return.
Since 1 tracker query results in multiple db queries, the db queries per second are even higher (metrics see below, but no real "queries per second"...).

Website is still functional during the tests (API responses, e.g. course-data, can be up to 100ms, but still feels fast). 

Only unrealistic part of this test is that this large amount of queries is done by only a rather small amount of connected clients (see 'ActiveConnectionCount'). In real environments it would be a much larger amount of connections but each making much less queries.

I will try to push it a bit further, but shown metrics can be assumed to work stable and I think this is already at a scale that fits our needs?

Let me know if you find something suspicious...

## Load Balancers
Note: 

* The shown values are per minute (e.g. requests per minute). The values from ALB1 and ALB2 have to be summed up (dns load balancer)
* Good: No ELB 5XX or HTTP 5XX -> All queries are processed

### ALB 1
![alb1](https://user-images.githubusercontent.com/780159/47785158-2250d600-dd08-11e8-950d-25d90c77a991.PNG)

### ALB 2
![alb2](https://user-images.githubusercontent.com/780159/47785169-2b41a780-dd08-11e8-8020-16abca8b4b39.PNG)

## Cassandra
I have not been able to find a real "queries per second" metric, but here is what mostly nodetool gives me.

### CPU
![cassandra-cpu](https://user-images.githubusercontent.com/780159/47785226-5deba000-dd08-11e8-85c0-330f37cff444.PNG)

#### netstats

![cassandra-nodetool-netstats](https://user-images.githubusercontent.com/780159/47785247-6f34ac80-dd08-11e8-9517-6ef65dc8d4a2.PNG)

#### tpstats

![cassandra-nodetool-tpstats](https://user-images.githubusercontent.com/780159/47785321-ac993a00-dd08-11e8-9eac-dbd521e26a49.PNG)

#### proxyhistograms

![cassandra-nodetool-proxyhistograms](https://user-images.githubusercontent.com/780159/47785374-d18dad00-dd08-11e8-89fa-bff1700c5d82.PNG)

#### tablestats (only global kespace parts, not all table stats)

![cassandra-nodetool-tablestats-overall](https://user-images.githubusercontent.com/780159/47785407-ebc78b00-dd08-11e8-9230-d17abb6fe29c.PNG)

**Comment by cyberjunk** [comment]
PS: There seem to be some improved/extended monitoring solutions for cassandra. May be we should look into setting up one of these (with detailed graphical visualizations, 24h monitoring etc., may be even with alarms or something. Because all this nodetool shell monitoring is really not convenient :-/

**Comment by dioptre** [comment]
Wonderful thanks mate. Would be good to try it out of debug mode too.
* How big did the disk get?
* What monitor did you want? I wanted to eventually upgrade these guys to datastax when it paid for itself. But keen on hearing your thoughts too.

**Comment by dioptre** [comment]
Let me know mate

**Comment by dioptre** [comment]
@cyberjunk ? You mentioned 2.5G in how long?

**Comment by dioptre** [comment]
ping @cyberjunk 

also note have updated the schema to be more balanced for updates on event - would be good to see if cassandra load decreased further still

**Comment by cyberjunk** [comment]
Old issue, closing.
For later testing, see: https://github.com/ichliebedich/hd/issues/181
