### ISSUE TITLE
Extend tracker to support SNS

### ISSUE THREAD

**Issue by dioptre** [ichliebedich/tracker#5]

**Comment by dioptre** [comment]
https://docs.aws.amazon.com/sns/latest/api/API_ConfirmSubscription.html
https://docs.aws.amazon.com/sdk-for-go/api/service/sns/#SNS.Publish

**Comment by cyberjunk** [comment]
@dioptre 

I've setup the SES -> SNS notifications, here are the SNS ARNs and details

### staging

Successful delivery:
>> arn:aws:sns:eu-west-1:735245989296:ses-deliver-staging

Failures we must handle:
>> arn:aws:sns:eu-west-1:735245989296:ses-complaint-staging
arn:aws:sns:eu-west-1:735245989296:ses-bounce-staging

### production

The production variants:
>> arn:aws:sns:eu-west-1:735245989296:ses-deliver-production
arn:aws:sns:eu-west-1:735245989296:ses-complaint-production
arn:aws:sns:eu-west-1:735245989296:ses-bounce-production

### Example for Deliver

Created using my private email address at Office 365

>>{"notificationType":"Delivery","mail":{"timestamp":"2018-11-05T12:14:19.595Z","source":"info@staging.homodea.com","sourceArn":"arn:aws:ses:eu-west-1:735245989296:identity/staging.homodea.com","sourceIp":"52.57.100.17","sendingAccountId":"735245989296","messageId":"01020166e3cb8bcb-c0bd8746-b7f1-41d9-b8c4-34dcdc288cb8-000000","destination":["clint.banzhaf@zds.de"]},"delivery":{"timestamp":"2018-11-05T12:14:22.463Z","processingTimeMillis":2868,"recipients":["clint.banzhaf@zds.de"],"smtpResponse":"250 2.6.0 <01020166e3cb8bcb-c0bd8746-b7f1-41d9-b8c4-34dcdc288cb8-000000@eu-west-1.amazonses.com> [InternalId=3693671875868, Hostname=DB6P190MB0279.EURP190.PROD.OUTLOOK.COM] 11443 bytes in 0.307, 36.323 KB/sec Queued mail for delivery","remoteMtaIp":"94.245.120.74","reportingMTA":"a50-184.smtp-out.eu-west-1.amazonses.com"}}

### Example for Bounce

Created using the bounce simulator address: bounce@simulator.amazonses.com
This includes additional info.

>> {"notificationType":"Bounce","bounce":{"bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"bounce@simulator.amazonses.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550 5.1.1 user unknown"}],"timestamp":"2018-11-05T12:26:59.738Z","feedbackId":"01020166e3d724f0-5023038d-cd88-483f-9451-cdc9a34312e8-000000","remoteMtaIp":"205.251.242.49","reportingMTA":"dsn; a50-184.smtp-out.eu-west-1.amazonses.com"},"mail":{"timestamp":"2018-11-05T12:26:58.000Z","source":"info@staging.homodea.com","sourceArn":"arn:aws:ses:eu-west-1:735245989296:identity/staging.homodea.com","sourceIp":"18.185.215.138","sendingAccountId":"735245989296","messageId":"01020166e3d72118-47c3e4e9-5351-434b-8a12-bbfaaabf5d16-000000","destination":["bounce@simulator.amazonses.com"],"headersTruncated":false,"headers":[{"name":"Date","value":"Mon, 5 Nov 2018 12:26:58 +0000"},{"name":"From","value":"info@staging.homodea.com"},{"name":"To","value":"bounce@simulator.amazonses.com"},{"name":"Message-ID","value":"<929129892.926604.1541420818886.JavaMail.ec2-user@ip-10-0-96-165.eu-west-1.compute.internal>"},{"name":"Subject","value":"Bitte bestaetigen Sie Ihre HOMODEA Anmeldung."},{"name":"MIME-Version","value":"1.0"},{"name":"Content-Type","value":"multipart/alternative;  boundary=\"----=_Part_926603_1184264217.1541420818885\""},{"name":"Content-Transfer-Encoding","value":"quoted-printable"}],"commonHeaders":{"from":["info@staging.homodea.com"],"date":"Mon, 5 Nov 2018 12:26:58 +0000","to":["bounce@simulator.amazonses.com"],"messageId":"<929129892.926604.1541420818886.JavaMail.ec2-user@ip-10-0-96-165.eu-west-1.compute.internal>","subject":"Bitte bestaetigen Sie Ihre HOMODEA Anmeldung."}}}

**Comment by cyberjunk** [comment]
@dioptre 

Andrew, it's also possible to subscribe HTTPS endpoints in SNS.
This might be a lot easier than register and read from SNS directly?
SNS then would simply send the notification as JSON using HTTPS POST to our specified tracker URL...

See:
https://docs.aws.amazon.com/en_us/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html

**Comment by dioptre** [comment]
ok had thoughts on this, we are not allowed to mix the analytics with the business base functionality due to GDPR (maybe) as discussed with @hilsbos 

so we'll need to setup an api endpoint with maybe basic auth in the api repo that can do the management of the user/remove from mailing list etc that then calls the tracker, and critically also passes through the last visitor id for that user/email

i've de-identified the usernames and the emails in the upstream branch but lets chat about it

**Comment by cyberjunk** [comment]
>> so we'll need to setup an api endpoint with maybe basic auth in the api repo that can do the management of the user/remove from mailing list etc that then calls the tracker, and critically also passes through the last visitor id for that user/email

Yes, I guess it would have to be basic HTTP auth then, because I can not provide anything but a plain URL when subscribing an endpoint to the SNS topic.

However, it's also possible to subscribe a AWS Lambda Function to the SNS topics, so that it is called for every bounce, complaint or successful delivery. 

We could also use such a Lambda function for writing a more custom message to our API endpoint or may be even to directly write to cassandra or nats - more difficult, due to access to local subnets, special nodejs packages etc., but possible?

**Comment by cyberjunk** [comment]
See https://github.com/ichliebedich/api/pull/93
For here suggested API endpoint routes for AWS SNS notifications, protected by basic HTTP auth

**Comment by cyberjunk** [comment]
Closing this. Tracker does not support SNS, problem was solved differently.
See ichliebedich/api#93 ichliebedich/api#99
